const express = require('express');
const router = express.Router();

const { createUser, UserData, UserpersonalData, UpdateUser, UserSpecificData, UserFilterData, deleteUserData, UserMatch, UserLookup, } = require("../controller/userController")
const { createEvent, EventData, UpdateEvent } = require("../controller/eventController");
const { createBooking, BookingData, bookingFilterData, UpdateBooking } = require("../controller/bookingController");
const { createDetail } = require("../controller/personaldtlController");
const { Status, StatusData, UpdateStatusData, statusMatch, taskLookup, tasknelookup } = require("../controller/taskController");
router.post(
    "/addDetail",
    createUser
)
router.post(
    "/event",
    createEvent
)
router.post(
    "/booking",
    createBooking
)
router.post(
    "/addPersonaldetail",
    createDetail
)
router.get(
    "/userdata/:id",
    UserData
)
router.get(
    "/userspecificData/:id",
    UserSpecificData
)
router.get(
    "/userFilter",
    UserFilterData
)
router.get(
    "/eventdata/:id",
    EventData
)
router.get(
    "/bookingdata/:id",
    BookingData
)
router.get(
    "/bookingfilter",
    bookingFilterData
)
router.get(
    "/personalData/:id",
    UserpersonalData
)
router.patch(
    "/updateUser",
    UpdateUser
)
router.patch(
    "/updateEvent",
    UpdateEvent
)
router.patch(
    "/updateBooking",
    UpdateBooking
)
router.delete(
    "/deleteUser/:id",
    deleteUserData
)
router.get(
    "/aggregate/matchuser",
    UserMatch
)
router.get(
    "/aggregate",
    UserLookup
)
router.get(
    "/task/lookup",
    taskLookup
)
router.get(
    "/task/ne/lookup",
    tasknelookup
)
router.post(
    "/create/status",
    Status
)
router.get(
    "/statusdata/:id",
    StatusData
)
router.patch(
    "/updatestatus",
    UpdateStatusData
)
router.get(
    "/check/status",
    statusMatch
)
module.exports = router;